classdef Main < ...
    TestConfig & ...
    TestConnection & ...
    TestERD & ...
    TestExternalFile & ...
    TestExternalS3 & ...
    TestFetch & ...
    TestProjection & ...
    TestTls & ...
    TestUuid
end