classdef Main < ...
    TestConfig & ...
    TestConnection & ...
    TestDelete & ...
    TestDeclaration & ...
    TestERD & ...
    TestExternalFile & ...
    TestExternalS3 & ...
    TestFetch & ...
    TestPopulate & ...
    TestProjection & ...
    TestRelationalOperand & ...
    TestSchema & ...
    TestTls & ...
    TestUuid & ...
    TestBlob & ...
    TestRelationalOperator
end