classdef Main < ...
    TestConfig & ...
    TestConnection & ...
    TestERD & ...
    TestExternalFile & ...
    TestExternalS3 & ...
    TestFetch & ...
    TestPopulate & ...
    TestProjection & ...
    TestRelationalOperand & ...
    TestSchema & ...
    TestTls & ...
    TestUuid
end
