classdef TestExternalS3 < Prep
    % TestExternalS3 tests scenarios related to external S3 store.
    methods (Test)
        % function TestExternalS3_testRemote(testCase)
        %     st = dbstack;
        %     disp(['---------------' st(1).name '---------------']);
        %     TestExternalFile.TestExternalFile_checks(testCase, 'new_remote', ...
        %         'blobCache');
        % end
        function TestExternalS3_testRemoteDefault(testCase)
            st = dbstack;
            disp(['---------------' st(1).name '---------------']);
            TestExternalFile.TestExternalFile_checks(testCase, 'new_remote_default', ...
                'blobCache');
        end
        function TestExternalS3_testBackward(testCase)
            st = dbstack;
            disp(['---------------' st(1).name '---------------']);
            TestExternalFile.TestExternalFile_checks(testCase, 'remote', 'cache');
        end
        function TestExternalS3_testBackwardDefault(testCase)
            st = dbstack;
            disp(['---------------' st(1).name '---------------']);
            TestExternalFile.TestExternalFile_checks(testCase, 'remote_default', ...
                'cache');
        end
        function TestExternalS3_testLocationFlexibility(testCase)
            st = dbstack;
            disp(['---------------' st(1).name '---------------']);
            location_values = {...
                'leading/slash/test',...
                '/leading/slash/test',...
                'leading\slash\test',...
                'f:\leading\slash\test',...
                'f:\leading/slash\test',...
                '/',...
                'C:\',...
                ''...
            };
            rel_path = 'does/this/work';
            for v = location_values
                s3Obj = dj.store_plugins.S3(struct(...
                    'datajoint_type', 'blob', ...
                    'protocol', 's3', ...
                    'location', v, ...
                    'endpoint', testCase.S3_CONN_INFO.endpoint, ...
                    'bucket', testCase.S3_CONN_INFO.bucket, ...
                    'access_key', testCase.S3_CONN_INFO.access_key, ...
                    'secret_key', testCase.S3_CONN_INFO.secret_key, ...
                    'secure', false, ...
                    'subfolding', [1;1] ...
                ));
                if length(v{1}) > 6
                    testCase.verifyEqual(s3Obj.make_external_filepath(rel_path),  ...
                        ['/' testCase.S3_CONN_INFO.bucket '/leading/slash/test' '/' rel_path]);
                else
                    testCase.verifyEqual(s3Obj.make_external_filepath(rel_path), ...
                        ['/' testCase.S3_CONN_INFO.bucket '/' rel_path]);
                end
            end
        end
    end
end