function s = hash(data, inputType)
if nargin<2
    inputType = 'array';
end
s = strrep(strrep(...
    dj.lib.DataHash(data, struct('Input', inputType, 'Method', 'SHA-256', 'Format', 'base64')), ...
    '/', '_'), ...
    '+', '-');  % make URL safe