classdef Main < ...
    tests.TestConfig & ...
    tests.TestConnection & ...
    tests.TestERD & ...
    tests.TestExternalFile & ...
    tests.TestExternalS3 & ...
    tests.TestFetch & ...
    tests.TestProjection & ...
    tests.TestTls & ...
    tests.TestUuid
end