% dj.internal.File - an external storage class for local file stores.
classdef File
    properties (Hidden, Constant)
        validation_config = struct( ...
            'store_config', struct( ...
                'protocol', struct( ...
                    'required', true, ...
                    'type_check', @(x) ischar(x) ...
                ), ...
                'location', struct( ...
                    'required', true, ...
                    'type_check', @(x) ischar(x) ...
                ) ...
            ), ...
            'type_config', struct( ...
                'blob', struct( ...
                    'subfolding', struct( ...
                        'required', false, ...
                        'type_check', @(x) all(floor(x) == x), ...
                        'default', [2, 2] ...
                    ), ...
                    'cache', struct( ...
                        'required', false, ...
                        'type_check', @(x) ischar(x), ...
                        'default', [] ...
                    ) ...
                ) ...
            ) ...
        )
    end
    properties
        protocol
        location
        blob_config
    end
    methods
        function file_store = File(config)
            file_store.protocol = config.store_config.protocol;
            file_store.location = config.store_config.location;
            file_store.blob_config = config.type_config.blob;
        end
    end
end
